project:
  type: website

website:
  title: "CAPSUS"
  favicon: "images/favicon.ico"
  navbar:
    logo: "images/Menu-Logo-Capsus.png"
    background: "#00495a"
    left:
      - href: index.qmd
        text: "Home"
      - href: portfolio-en.qmd
        text: "Projects"
      - href: expertise-en.qmd
        text: "Expertise"
      - href: careers-en.qmd
        text: "Careers"
    right:
      - href: portfolio-es.qmd
        text: "ES"
        
format:
  html:
    theme: custom.scss
    minimal: true # Strips out heavy default JS/CSS for a low-carbon footprint