---
title: "Aviso de Privacidad"
toc: true
---

**Última actualización:** 14 de julio de 2020

### Responsable del Tratamiento de Datos
**CAPSUS, S.C.**, con domicilio en Boulevard Manuel Ávila Camacho 118, Int. 1604, Lomas de Chapultepec, Alcaldía Miguel Hidalgo, C.P. 11000, Ciudad de México, México, y portal web [www.capsus.mx](https://www.capsus.mx), es responsable del uso y protección de sus datos personales.

### Primera: Finalidad del uso de datos personales
Los datos personales que recabamos de usted, los utilizaremos para verificar y confirmar su identidad para la elaboración de contratos, creación y conservación del expediente administrativo, y para los servicios profesionales que contrata con nosotros.

### Segunda: Finalidades secundarias
De manera adicional, utilizaremos su información para mercadotecnia, encuestas de satisfacción y prospección comercial. La negativa para el uso de sus datos personales para estas finalidades no podrá ser motivo para que le neguemos los servicios solicitados.

### Tercera: Datos personales recabados
Para las finalidades anteriores, solicitaremos: nombre completo, correo electrónico, teléfono, domicilio, RFC y datos bancarios.

### Cuarta: Ejercicio de Derechos ARCO
Usted tiene derecho a conocer qué datos personales tenemos, solicitar su corrección, cancelación u oponerse a su uso (Derechos ARCO). Para el ejercicio de los derechos ARCO, envíe un correo electrónico a [ideas@capsus.mx](mailto:ideas@capsus.mx) o comuníquese al teléfono +52 (55) 47 44 48 30.

### Quinta: Revocación del consentimiento
Puede revocar su consentimiento para el tratamiento de sus datos personales en cualquier momento presentando su solicitud por correo electrónico a [ideas@capsus.mx](mailto:ideas@capsus.mx).
