---
title: "Agenda de Investigación de Energía Limpia y Eficiencia Energética"
client: "Sener, Grupo Banco Mundial y Banco Interamericano de Desarrollo (BID)"
location: "Campeche, Quintana Roo, Tabasco, Yucatán, México"
year: "2016"
categories: ["Energía Renovable"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Agenda de Investigación de Energía Limpia y Eficiencia Energética",
  "sponsor": "Sener, Grupo Banco Mundial y Banco Interamericano de Desarrollo (BID)",
  "spatialCoverage": "Campeche, Quintana Roo, Tabasco, Yucatán, México"
}
</script>

Se realizó un estudio de gabinete y de campo para proponer una agenda de investigación y desarrollo a la Secretaría de Energía, para la región de la Península de Yucatán. Para este proyecto se analizó la vocación natural de la región para la producción de energía renovable, la dinámica económica para identificar las características de la demanda energética, las empresas establecidas y los proyectos de inversión existentes, la competitividad regional en la materia, la infraestructura existente, los esfuerzos y resultados de investigación, las necesidades empresariales y la capacidad instalada de las instituciones académicas. El resultado final fue el desarrollo de Programas Estatales de Inversión en Energías Limpias, basados en una Evaluación de las Necesidades Regionales. Este proyecto se trabajó con PRETIUM.
