---
title: "Análisis de Gobernanza Ambiental en Quintana Roo dentro del Marco del Plan Estratégico de Desarrollo Sostenible 2050"
client: "Ciudadanos por la Transparencia (ONG)"
location: "Quintana Roo, México"
year: 2024
categories: ["Políticas Públicas"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Análisis de Gobernanza Ambiental en Quintana Roo dentro del Marco del Plan Estratégico de Desarrollo Sostenible 2050",
  "sponsor": "Ciudadanos por la Transparencia (ONG)",
  "spatialCoverage": "Quintana Roo, México"
}
</script>

Este proyecto consistió en la creación del capítulo de Gobernanza Ambiental para el Plan Estratégico de Desarrollo Sostenible de Quintana Roo 2050. Implicó una investigación documental exhaustiva sobre los principales desafíos ambientales del estado y un mapeo detallado del marco regulatorio ambiental y las políticas públicas relevantes. CAPSUS lideró el proyecto, diseñando e implementando instrumentos para la cogeneración de información y facilitando procesos de participación ciudadana con actores clave de los sectores privado, público y civil en las diferentes regiones del estado. CAPSUS también desarrolló líneas de acción estratégicas y recomendaciones de política pública orientadas a fortalecer la relevancia y efectividad multisectorial de la gobernanza ambiental en Quintana Roo.
