---
title: "Asesoría Técnica en la Elaboración de Programas de Acción Climática"
client: "La Comisión Europea y los gobiernos municipales de: Bahía de Banderas (Nayarit), Culiacán (Sinaloa), Juárez (Chihuahua), Ciudad Madero (Tamaulipas) y Zapopan (Jalisco)"
location: "Bahía de Banderas (Nayarit), Culiacán (Sinaloa), Juárez (Chihuahua), Ciudad Madero (Tamaulipas) y Zapopan (Jalisco), México."
year: 2019-2020
categories: ["Cambio Climático"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Asesoría Técnica en la Elaboración de Programas de Acción Climática",
  "sponsor": "La Comisión Europea y los gobiernos municipales de: Bahía de Banderas (Nayarit), Culiacán (Sinaloa), Juárez (Chihuahua), Ciudad Madero (Tamaulipas) y Zapopan (Jalisco)",
  "spatialCoverage": "Bahía de Banderas (Nayarit), Culiacán (Sinaloa), Juárez (Chihuahua), Ciudad Madero (Tamaulipas) y Zapopan (Jalisco), México."
}
</script>

Se asesoró y capacitó a cinco municipios mexicanos para la elaboración de sus Planes de Acción Climática locales. El proceso incluyó la compilación de un inventario de emisiones de gases de efecto invernadero, un análisis de riesgos y vulnerabilidades climáticas, la elaboración de medidas y estrategias de mitigación y resiliencia climática, la priorización de estas y las estrategias de comunicación e interacción comunitaria. El proyecto se llevó a cabo en colaboración con el Pacto Global de los Alcaldes por el Clima y la Energía (GCoM), y el Programa de Cooperación Urbana Internacional (IUC).
