---
title: "Catálogo de las mejores tecnologías para el manejo eficiente de agua"
client: "Amigos de Sian Ka’an A. C. (ONG Nacional para la Conservación Ambiental)"
location: "Quintana Roo, México"
year: "2020-2021"
categories: ["Desarrollo de Capacidades"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Catálogo de las mejores tecnologías para el manejo eficiente de agua",
  "sponsor": "Amigos de Sian Ka’an A. C. (ONG Nacional para la Conservación Ambiental)",
  "spatialCoverage": "Quintana Roo, México"
}
</script>

El objetivo de este proyecto fue evaluar los resultados de la primera etapa de un proyecto que construyó e instaló tecnologías para la gestión eficiente del agua en comunidades rurales del estado de Quintana Roo, México. Los resultados de esta evaluación ayudaron a desarrollar un informe de lecciones aprendidas. Considerando estas lecciones aprendidas, CAPSUS diseñó e implementó dos talleres con expertos nacionales e internacionales para definir un catálogo con las mejores tecnologías para instalar y construir en otras comunidades rurales de Quintana Roo, como una segunda etapa del proyecto.
