---
title: "Desarrollo de escenarios para viviendas resilientes y energéticamente eficientes para ciudades secundarias en Mongolia"
client: "Banco Mundial"
location: "Mongolia"
year: 2022-2023
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Desarrollo de escenarios para viviendas resilientes y energéticamente eficientes para ciudades secundarias en Mongolia",
  "sponsor": "Banco Mundial",
  "spatialCoverage": "Mongolia"
}
</script>

El proyecto apoya el desarrollo de viviendas resilientes, energéticamente eficientes, ecológicas y asequibles para los distritos *Ger* en las dos ciudades secundarias clave de Mongolia: Darkhan y Erdenet. El proyecto producirá una evaluación detallada para las ciudades que apoyan la priorización de la planificación y el desarrollo de viviendas asequibles con bajas emisiones de GEI y resistentes al cambio climático, en áreas *Ger* y áreas no *Ger*. Los resultados fortalecerán los programas de vivienda existentes e incentivarán el uso de soluciones resilientes y bajas en carbono. Este proyecto es consecuencia de un trabajo anterior realizado por CAPSUS en Mongolia.
