---
title: "Escenarios climáticamente inteligentes para viviendas asequibles en el sur de Sumatra, Indonesia"
client: "Banco Mundial"
location: "Palembang, Musi Rawas y Lubuklinggau, Indonesia"
year: "2022-2023"
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Escenarios climáticamente inteligentes para viviendas asequibles en el sur de Sumatra, Indonesia",
  "sponsor": "Banco Mundial",
  "spatialCoverage": "Palembang, Musi Rawas y Lubuklinggau, Indonesia"
}
</script>

El proyecto brinda apoyo a los gobiernos locales de Palembang, Musi Rawas y Lubuklinggau para generar una política integral de vivienda. A través de un enfoque holístico y climáticamente inteligente, el proyecto desarrolla una evaluación detallada de las ciudades para la identificación de ubicaciones estratégicas para inversiones de vivienda asequible. El objetivo es ayudar en la definición de proyectos de vivienda asequible, verde y energéticamente eficiente en estas ciudades para aumentar la competitividad regional, la resiliencia climática y el desarrollo sustentable. El trabajo también incluye el desarrollo de un análisis espacial para identificar ubicaciones prioritarias, la priorización de inversión, la estimación de objetivos de reducción de emisiones de GEI, la propuesta de lineamientos para proyectos de vivienda verdes y energéticamente eficientes, y el desarrollo de tres escenarios para la implementación de proyectos de vivienda asequible (condiciones actuales, tendencial, y escenarios climáticamente inteligentes).
