---
title: "Escenarios climáticamente inteligentes para viviendas ecológica y energéticamente eficientes en las Maldivas"
client: "Banco Mundial"
location: "Malé, Addu, y Fuvahmulah, Maldivas"
year: 2023-2024
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Escenarios climáticamente inteligentes para viviendas ecológica y energéticamente eficientes en las Maldivas",
  "sponsor": "Banco Mundial",
  "spatialCoverage": "Malé, Addu, y Fuvahmulah, Maldivas"
}
</script>

El proyecto apoya al Gobierno de Maldivas en el desarrollo de métricas que proporcionan análisis espacial socioeconómico y recomendaciones clave para informar la política nacional de vivienda. El trabajo proporciona información para un financiamiento más eficiente y eficaz de la vivienda en Malé (Malé, Hulhumalé, Thilafushi, Gulhi Falhu), Addu y Fuvahmulah. El proyecto desarrolla una evaluación detallada para las ciudades, esté prioriza la inversión en vivienda asequible, de bajas emisiones GEI y resiliente al cambio climático. El trabajo incluye la recopilación de datos; y el mapeo de desarrollo urbano y métricas de vulnerabilidad al riesgo climático; la planificación de escenarios para el desarrollo de vivienda; la evaluación de escenarios; el desarrollo de directrices técnicas de vivienda verde y energéticamente eficiente, así como la difusión de los resultados.
