---
title: "Escenarios de Crecimiento Urbano para Indonesia"
client: "Grupo Banco Mundial y Gobierno Nacional de Indonesia"
location: "Denpasar, Palau y Semarang, Indonesia"
year: "2017-2018"
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Escenarios de Crecimiento Urbano para Indonesia",
  "sponsor": "Grupo Banco Mundial y Gobierno Nacional de Indonesia",
  "spatialCoverage": "Denpasar, Palau y Semarang, Indonesia"
}
</script>

Escenarios de Crecimiento Urbano para Indonesia es un proyecto financiado por Corea, a través del Grupo Banco Mundial, el cual tiene como objetivo evaluar posibles patrones de desarrollo para las ciudades de Denpasar y Semarang. Se adaptaron dos herramientas –Suitability y Urban Performance y se desarrollaron escenarios de crecimiento urbano para visualizar los impactos de diferentes políticas públicas en las dimensiones ambiental, social y económica. Los escenarios evaluaron diferentes políticas urbanas en términos de disponibilidad de vivienda, eficiencia del agua, consumo de energía, balance de costos-ingresos y emisiones de gases de efecto invernadero, estimando así indicadores ambientales, sociales y económicos para cada escenario de crecimiento urbano. Además, se evaluaron los beneficios y las desventajas de diferentes combinaciones de políticas públicas, proyectos y condiciones para llegar a un consenso sobre la mejor ruta de desarrollo. Se instruyó a las partes interesadas sobre el uso de las herramientas de planificación urbana desarrolladas a través de varios talleres de desarrollo de capacidades.

Finalmente, como una extensión para Indonesia, se propusieron áreas para la reubicación de asentamientos de población en Palu después del terremoto y tsunami de 2018.
