---
title: "Estrategia de Sustentabilidad para el Centro Integralmente Planeado (CIP) Playa Espíritu"
client: "FONATUR"
location: "Sinaloa, México"
year: 2016
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Estrategia de Sustentabilidad para el Centro Integralmente Planeado (CIP) Playa Espíritu",
  "sponsor": "FONATUR",
  "spatialCoverage": "Sinaloa, México"
}
</script>

Diseño del Plan Maestro de un nuevo destino turístico, cuya extensión será mayor a las 2 mil hectáreas. El objetivo del proyecto es crear un diseño urbano-turístico que sea ejemplo del desarrollo sustentable, creando beneficios económicos, sociales y ambientales para la región. Como parte de los trabajos, se aportaron lineamientos de sustentabilidad, incluyendo el uso eficiente de recursos naturales y energéticos, análisis de certificaciones ambientales, y escenarios de desarrollo. El proyecto fue desarrollado en conjunto con a911, cadena+asociados, y 4s.
