---
title: "Evaluación de idoneidad para la ubicación de viviendas subsidiadas en Indonesia"
client: "Grupo Banco Mundial"
location: "Indonesia"
year: 2020
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Evaluación de idoneidad para la ubicación de viviendas subsidiadas en Indonesia",
  "sponsor": "Grupo Banco Mundial",
  "spatialCoverage": "Indonesia"
}
</script>

El objetivo principal del proyecto es analizar la idoneidad de la ubicación de proyectos de vivienda a partir de la herramienta de planeación urbana “Suitability”. La herramienta permite evaluar la ubicación de proyectos de vivienda con respecto a la cobertura de servicios, distancia a zonas urbanas y costo de la tierra, así como proporcionar recomendaciones que orienten a los gobiernos en términos de tipologías de vivienda basadas en la localización geográfica, características económicas y urbanas y con criterios de riesgos ambientales. Este proyecto es piloteado en 6 áreas metro.
