---
title: "Herramientas de Planificación Urbana \- Sesiones de Capacitación Demostrativa"
client: "Banco Mundial"
location: "Internacional"
year: 2024
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Herramientas de Planificación Urbana \- Sesiones de Capacitación Demostrativa",
  "sponsor": "Banco Mundial",
  "spatialCoverage": "Internacional"
}
</script>

El proyecto consistió en diseñar y programar tres herramientas de planificación urbana: 1\) Urban Performance (esta herramienta compara escenarios de crecimiento urbano y evalúa el impacto de los proyectos de inversión utilizando un conjunto de indicadores), 2\) Suitability (esta herramienta identifica los lugares más adecuados dentro de una ciudad para implementar proyectos de planificación urbana e inversiones), y 3\) CollabData (esta herramienta promueve la participación social y la comunicación en relación con las necesidades y prioridades de la comunidad). Además, el proyecto incluyó la planificación y realización de sesiones de capacitación para los actores interesados del Banco Mundial. Estas sesiones tenían como objetivo facilitar la transferencia de conocimiento para expertos y profesionales a través del desarrollo de materiales gráficos, materiales audiovisuales y actividades colaborativas.
