---
title: "Herramientas de planeación urbana como agentes de cambio: Datos espaciales colaborativos para el desarrollo urbano sustentable en Indonesia"
client: "Grupo Banco Mundial / Gobierno Nacional de Indonesia"
location: "Indonesia"
year: 2019-2020
categories: ["Datos y Tecnología"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Herramientas de planeación urbana como agentes de cambio: Datos espaciales colaborativos para el desarrollo urbano sustentable en Indonesia",
  "sponsor": "Grupo Banco Mundial / Gobierno Nacional de Indonesia",
  "spatialCoverage": "Indonesia"
}
</script>

En este proyecto se desarrolló un repositorio de información espacial basado en la web (Geoportal) además de tres herramientas de planificación urbana integradas en el Geoportal. La herramienta llamada “CollabMap” está destinada a favorecer la participación pública en los procesos de planificación urbana. La herramienta “Urban Hotspots” identifica la ubicación más adecuada dentro de una ciudad para llevar a cabo una actividad en específico, como la priorización de proyectos de inversión. La herramienta “Urban Performance” permite a los usuarios diseñar y evaluar escenarios urbanos para comparar el impacto de los proyectos de inversión a través de un conjunto de indicadores. El proyecto fue una colaboración con el Grupo Banco Mundial para apoyar a varias agencias y seis ciudades en Indonesia a mejorar el proceso de evaluación y aprobación de sus planes maestros.
