---
title: "Hoja de Ruta para la Energía Renovable Distribuida"
client: "IFC"
location: "México"
year: "2024"
categories: ["Energía Renovable"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Hoja de Ruta para la Energía Renovable Distribuida",
  "sponsor": "IFC",
  "spatialCoverage": "México"
}
</script>

El proyecto se desarrolló con Econoler y Coenergia, con el objetivo de elaborar una hoja de ruta para promover la energía renovable distribuida en México. Durante el proyecto, el equipo identificó a los actores relevantes y realizó una investigación sobre las características actuales del mercado, sus desafíos, oportunidades y acciones potenciales que podrían aumentar la participación de la energía renovable implementada por el sector privado. A lo largo del proyecto, el equipo realizó un taller y varias entrevistas con expertos de la industria, funcionarios públicos, instituciones financieras, desarrolladores y consumidores para comprender los desafíos existentes y cómo superarlos. El producto final fue una Hoja de Ruta que recomienda una lista específica de acciones, hitos y políticas necesarias para aumentar la inversión privada en energía renovable distribuida en México.
