---
title: "Modelo de Crecimiento Urbano y Expansión Urbana Sostenible para el Reino Hachemita de Jordania"
client: "Banco Mundial"
location: "Amman, Jordania"
year: "2022"
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Modelo de Crecimiento Urbano y Expansión Urbana Sostenible para el Reino Hachemita de Jordania",
  "sponsor": "Banco Mundial",
  "spatialCoverage": "Amman, Jordania"
}
</script>

El objetivo de este proyecto es proporcionar información analítica al Informe de desarrollo del Cambio Climático de Jordania (CCDR), centrándose en los sectores urbano, de transporte y energético, y otras actividades relacionadas que lleva a cabo el Banco Mundial sobre el cambio climático y las ciudades en Jordania. El análisis y las recomendaciones se desarrollaron utilizando herramientas y metodologías para evaluar los vínculos espaciales y sectoriales entre Amán y las ciudades vecinas. El análisis se enfocó en 1) identificar el potencial para la reducción de emisiones de Gases de Efecto Invernadero (GEI) de la expansión urbana y los servicios de la ciudad, incluyendo las mejoras en el transporte y la energía; 2) determinar los beneficios colaterales potenciales asociados a las estrategias de reducción de emisiones de GEI; y 3) seleccionar prioridades clave de planificación urbana e infraestructura para guiar políticas e intervenciones.
