---
title: "Perfil Metropolitano Versión 2"
client: "Banco Mundial y el Fondo de Crecimiento Verde de Corea"
location: "México"
year: "2017-2018"
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Perfil Metropolitano Versión 2",
  "sponsor": "Banco Mundial y el Fondo de Crecimiento Verde de Corea",
  "spatialCoverage": "México"
}
</script>

El Perfil Metropolitano Versión 2 fue un proyecto financiado por el “Energy Sector Management Assistance Program (ESMAP)” a través del Banco Mundial. Tuvo como objetivo evaluar posibles patrones de desarrollo para las ciudades mexicanas en la búsqueda de identificar las opciones más sostenibles. La Comisión Nacional de Vivienda (CONAVI) fue la dependencia nacional designada como vínculo entre los diferentes actores, así como la principal contraparte del proyecto. La segunda versión del Perfil Metropolitano analiza el crecimiento tendencial, al año 2030, de 37 zonas metropolitanas de México y lo compara con escenarios de crecimiento compacto o conforme a los Programas de Desarrollo Urbano vigentes. Se utilizan más de quince indicadores para evaluar los escenarios. Adicionalmente, incluye dos estudios de caso, Mérida y Tijuana, que incluyen escenarios definidos con los institutos de planeación locales y estrategias de eficiencia energética. En el caso de Mérida, el estudio se utilizó para comparar los beneficios del nuevo Programa de Desarrollo Urbano contra el anterior.
