---
title: "Programa de Gestión Ambiental de la Calidad del Aire de la Zona Metropolitana del Valle de México 2021-2030 (ProAire ZMVM 2021-2030)"
client: "Secretaría de Medio Ambiente de la Ciudad de México (SEDEMA)"
location: "Ciudad de México"
year: "2020"
categories: ["Cambio Climático"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Programa de Gestión Ambiental de la Calidad del Aire de la Zona Metropolitana del Valle de México 2021-2030 (ProAire ZMVM 2021-2030)",
  "sponsor": "Secretaría de Medio Ambiente de la Ciudad de México (SEDEMA)",
  "spatialCoverage": "Ciudad de México"
}
</script>

El Programa para Mejorar la Calidad del Aire de la Zona Metropolitana del Valle de México (ProAire ZMVM) incluye las 16 alcaldías de la Ciudad de México, 59 municipios conurbados del estado de México y Tizayuca, Hidalgo. Para ello se realizó un diagnóstico de la calidad del aire en la ZMVM que incluyó el análisis de los resultados del inventario de emisiones, el análisis institucional, las capacidades presupuestales y operativas, así como los resultados de las estaciones de monitoreo atmosférico. Con base en el diagnóstico se desarrolló la estrategia metropolitana para reducir la emisión de contaminantes atmosféricos locales, revertir las tendencias de deterioro, proteger la salud pública de la población y fortalecer el monitoreo. Las estrategias y medidas de política pública incluidas en el Programa fueron evaluadas y priorizadas en términos de su potencial de reducción de emisiones y costo estimado de implementación.
