---
title: "Promoción de soluciones habitacionales sustentables para familias de bajos recursos en México"
client: "GIZ"
location: "México"
year: "2020-2021"
categories: ["Planificación Urbana"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Promoción de soluciones habitacionales sustentables para familias de bajos recursos en México",
  "sponsor": "GIZ",
  "spatialCoverage": "México"
}
</script>

El proyecto apoya a la Comisión Nacional de Vivienda (CONAVI) a promover soluciones de vivienda más sostenibles para familias de bajos recursos en 15 municipios mexicanos seleccionados. El trabajo se enfoca en ajustar y refinar los subsidios habitacionales existentes para incorporar elementos de sustentabilidad en la autoconstrucción y mejoramiento de viviendas de interés social, incluyendo diseño bioclimático, materiales de construcción sustentables y ecotecnologías, para reducir el consumo energético de las familias y aumentar la eficiencia energética de las viviendas. El proyecto se enfocó en el rediseño de manuales de sustentabilidad habitacional y el desarrollo de escenarios relacionados con soluciones pasivas regionalizadas para lograr viviendas energéticamente eficientes y cómodas para hogares de bajos recursos.
