---
title: "Financing Energy for Low-Carbon Investment - Cities Advisory Facility (FELICITY)"
client: "German Agency for International Cooperation (GIZ), European Investment Bank (EIB)"
location: "Mexico"
year: "2018"
categories: ["Sustainable Finance"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Financing Energy for Low-Carbon Investment - Cities Advisory Facility (FELICITY)",
  "sponsor": "German Agency for International Cooperation (GIZ), European Investment Bank (EIB)",
  "spatialCoverage": "Mexico"
}
</script>

A feasibility status review and opinion on environmental, social, economic, and legal aspects of two investment projects was done for the GIZ and EIB initiative Financing Energy for Low-carbon Investment - Cities Advisory Facility (FELICITY). One project consists of a biodigester of organic waste that aims to reduce the amount of urban solid waste sent to landfills, produce electricity and mitigate air pollutants. The second project was an energy saving scheme in public buildings that would be financed by the issuance of a green bond.
