---
title: "Social Communication and Participation Strategy for Asunción, Paraguay"
client: "Inter-American Development Bank (IADB)"
location: "Asuncion, Paraguay"
year: 2019-2021
categories: ["Capacity Development"]
---

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Project",
  "name": "Social Communication and Participation Strategy for Asunción, Paraguay",
  "sponsor": "Inter-American Development Bank (IADB)",
  "spatialCoverage": "Asuncion, Paraguay"
}
</script>

The social communication and participation strategy is designed and implemented in Tacumbú, Asunción, Paraguay. This strategy is composed of three mechanisms 1) Social communication and information, 2) Public consultation and participation, and 3) Grievance redressal. These mechanisms are supported by a digital platform named CollabMap. The strategy seeks to strengthen communication and information management, social inclusion, attention to complaints, and to promote the active participation of the population around a Housing Program and related projects for neighborhood consolidation. Derived from a contract extension, additional urban planning tools are being implemented to gather field and institutional information, which will advance informed decision making for vulnerable groups during the COVID-19 crisis and recovery stage.
